spring:
  datasource:
#    driverclassname: "com.mysql.cj.jdbc.Driver"
    url: jdbc:mysql://10.255.128.155:3306/cloud?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: cloud_test
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  redis:
    host: 47.94.248.206 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）

user:
  url: "http://dev.paas.gwm.cn"
  check: "/api/v1/system/user/power_check"
  quotas: "/api/v1/system/group/quotas"

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
#dop:
#  url: http://testdop.gwmdc.com/%s
#  bk_app_code: bk_nodeman
#  bk_app_secret: 7e5f7ba7-9eb2-4931-a1a8-ffae19c0b79f
#  bk_username: admin
#  bk_biz_id: 26
#  streamsets_template_id: 172
dop:
  url: http://dop.gwmdc.com/%s
  bk_app_code: bk_nodeman
  bk_app_secret: 9701ccf9-6c39-4f99-8127-d08cd3517692
  bk_username: admin
  bk_biz_id: 319
  streamsets_template_id: 10040

streamsets:
  imageUuid: f12cef91-ec55-4b17-bb67-aec9c439726d
  network: dc270a7d-1585-4e16-980f-ddcc1b2b5891
cloud:
  api: http://10.255.128.190:8090/%s

#ribbon的超时时间
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000

swagger:
  enable: true


logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.gwm.cloudstreamsets: debug