spring:
  datasource:
    url: jdbc:mysql://10.255.128.190:3306/cloud?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: dj
    password: 1q2w3e4r
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  redis:
    host: 10.255.128.190 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: 123456 # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）

user:
  url: "http://dev.paas.gwm.cn"
  check: "/api/v1/system/user/power_check"
  quotas: "/api/v1/system/group/quotas"

#底层链接地址
ecs:
  url: "http://10.255.128.191:8080:%s"

#rsas平台相关参数
rsas:
  username: "api"
  password: "xxDX123@"
  url: "https://10.255.19.172"
  #报表相关
  report:
    generate: "/api/generate_report/" #生成报表
    status: "/api/get_report_progress/report_id/"  #进度
    download: "/api/download_report/report_id/%s/report_type/%s" #下载
  task:
    create: "/api/task/vul/create" #任务创建
    status: "/api/task/status/" #任务状态

#aliyun ak
aliyun:
  accessKeyId: "LTAI4GBGmkd5yuojsua4oK1K"
  secret: "PzSgLCPo7TSk52YXiaukJXHxXJte1W"
  regionId: "cn-beijing"

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml

#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000

swagger:
  enable: true

logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.gwm.cloudecs: info